server:
  port: 9009

spring:
  main:
    web-application-type: reactive

  application:
    name: BANK-GATEWAY

  cloud:
    gateway:
      routes:
        - id: APPLICATION-STATUS-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/applicationstatus/**
          filters:
            - name: CircuitBreaker
              args:
                name: APPLICATION-STATUS-SERVICE
                fallbackUri: forward:/applicationStatusFallback

        - id: APPLICATION-DETAILS-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/applicationdetails/**
          filters:
            - name: CircuitBreaker
              args:
                name: APPLICATION-DETAILS-SERVICE
                fallbackUri: forward:/applicationDetailsFallback

        - id: LOAN-CUSTOMER-SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/loancustomer/**
          filters:
            - name: CircuitBreaker
              args:
                name: LOAN-CUSTOMER-SERVICE
                fallbackUri: forward:/loanCustomerFallback

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

  timelimiter:
    configs:
      default:
        timeout-duration: 5s

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
